import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TodoPro from "@/providers/TodoPro";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TodoPro>
          <Toaster
            position="top-right"
            reverseOrder={false}
          />
          {children}
        </TodoPro>
      </body>
    </html>
  );
}
